In [1]:
import numpy as np

In [2]:
a=np.arange(1,10)

In [3]:
x=a.reshape(3,3)

In [4]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
a=np.arange(2,11)

In [6]:
y=a.reshape(3,3)

In [7]:
y

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [8]:
print(np.add(x,y))

[[ 3  5  7]
 [ 9 11 13]
 [15 17 19]]


In [9]:
print(np.subtract(x,y))

[[-1 -1 -1]
 [-1 -1 -1]
 [-1 -1 -1]]


In [10]:
print(np.multiply(x,y))

[[ 2  6 12]
 [20 30 42]
 [56 72 90]]


In [11]:
print(np.divide(x,y))

[[0.5        0.66666667 0.75      ]
 [0.8        0.83333333 0.85714286]
 [0.875      0.88888889 0.9       ]]


In [12]:
print(np.dot(x,y))

[[ 36  42  48]
 [ 81  96 111]
 [126 150 174]]


In [13]:
import pandas as pd

In [14]:
s=pd.Series()
print(s)

Series([], dtype: float64)


C:\Users\Admin\AppData\Local\Temp\ipykernel_6296\2242303654.py:1: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  s=pd.Series()


In [15]:
data=np.array(['A','B','C','d','E'])
print(data)

['A' 'B' 'C' 'd' 'E']


In [16]:
data.ndim

1

In [17]:
s=pd.Series(data)
print(s)

0    A
1    B
2    C
3    d
4    E
dtype: object


In [18]:
x=pd.DataFrame(data)
print(x)

   0
0  A
1  B
2  C
3  d
4  E


In [20]:
data=np.array(['A','B','C','d','E'])
y=pd.Series(data,index=[100,101,102,103,104])
print(y)

100    A
101    B
102    C
103    d
104    E
dtype: object


In [22]:
data={'a':0,'b':1,'c':2}
data

{'a': 0, 'b': 1, 'c': 2}

In [23]:
type(data)

dict

In [24]:
x=pd.Series(data)
print(x)

a    0
b    1
c    2
dtype: int64


In [25]:
s=pd.Series(5,index=[0,1,2,3,4])
print(s)

0    5
1    5
2    5
3    5
4    5
dtype: int64


In [29]:
l=[10,20,30,40,50,60,70]
s=pd.Series(l,index=['a','b','c','d','e','f','g'])

In [30]:
s

a    10
b    20
c    30
d    40
e    50
f    60
g    70
dtype: int64

In [33]:
df=pd.DataFrame()
print(df)

Empty DataFrame
Columns: []
Index: []


In [36]:
data=[1,2,3,4,5,6,7,8,9]
type(data)

list

In [37]:
df=pd.DataFrame(data)
print(df)

   0
0  1
1  2
2  3
3  4
4  5
5  6
6  7
7  8
8  9


In [40]:
data=[['Aadarsh',20],['Ajit',80],['Abhay',200],['ankit',27],['Hemanth',10],['Anuj',40]]
df=pd.DataFrame(data)
print(df)

         0    1
0  Aadarsh   20
1     Ajit   80
2    Abhay  200
3    ankit   27
4  Hemanth   10
5     Anuj   40


In [41]:
data=[['Aadarsh',20],['Ajit',80],['Abhay',200],['ankit',27],['Hemanth',10],['Anuj',40]]
df=pd.DataFrame(data,columns=['Name','Age'])
print(df)

      Name  Age
0  Aadarsh   20
1     Ajit   80
2    Abhay  200
3    ankit   27
4  Hemanth   10
5     Anuj   40


In [42]:
d={'aa':1}
d

{'aa': 1}

In [43]:
d['bb']=2

In [44]:
d

{'aa': 1, 'bb': 2}

In [53]:
data=[['Aadarsh',20],['Ajit',80],['Abhay',200],['ankit',27],['Hemanth',10],['Anuj',40]]
df=pd.DataFrame(data,columns=['Name','Age'],dtype=float,index=['r1','r2','r3','r4','r5','r6'])
print(df)

       Name    Age
r1  Aadarsh   20.0
r2     Ajit   80.0
r3    Abhay  200.0
r4    ankit   27.0
r5  Hemanth   10.0
r6     Anuj   40.0


C:\Users\Admin\AppData\Local\Temp\ipykernel_6296\599077160.py:2: FutureWarning: Could not cast to float64, falling back to object. This behavior is deprecated. In a future version, when a dtype is passed to 'DataFrame', either all columns will be cast to that dtype, or a TypeError will be raised.
  df=pd.DataFrame(data,columns=['Name','Age'],dtype=float,index=['r1','r2','r3','r4','r5','r6'])


In [54]:
data={'Name':['Aadarsh','Ajit','Aman','Hemanth','Anuj'],'Age':[20,80,19,50,90]}
data

{'Name': ['Aadarsh', 'Ajit', 'Aman', 'Hemanth', 'Anuj'],
 'Age': [20, 80, 19, 50, 90]}

In [55]:
df=pd.DataFrame(data)
print(df)

      Name  Age
0  Aadarsh   20
1     Ajit   80
2     Aman   19
3  Hemanth   50
4     Anuj   90


In [56]:
df

Name  Age
0  Aadarsh   20
1     Ajit   80
2     Aman   19
3  Hemanth   50
4     Anuj   90

In [57]:
data=[{'a':1,'b':2},{'a':5,'b':10,'c':20}]
df=pd.DataFrame(data)
print(df)

   a   b     c
0  1   2   NaN
1  5  10  20.0


In [58]:
data=[{'a':1,'b':2,'c':3},{'a':5,'b':10,'c':20}]
df=pd.DataFrame(data)
print(df)

   a   b   c
0  1   2   3
1  5  10  20


In [59]:
d={'one':pd.Series([1,2,3],index=['a','b','c']),'two':pd.Series([1,2,3,4],index=['a','b','z','d'])}
df=pd.DataFrame(d)
print(df)

   one  two
a  1.0  1.0
b  2.0  2.0
c  3.0  NaN
d  NaN  4.0
z  NaN  3.0


In [60]:
df

one  two
a  1.0  1.0
b  2.0  2.0
c  3.0  NaN
d  NaN  4.0
z  NaN  3.0

In [64]:
d['three']=pd.Series([10,11,12,13,14],index=['a','b','c','d','z'])
df=pd.DataFrame(d)
df

one  two  three
a  1.0  1.0     10
b  2.0  2.0     11
c  3.0  NaN     12
d  NaN  4.0     13
z  NaN  3.0     14

In [65]:
d.keys()

dict_keys(['one', 'two', 'three'])

In [66]:
d.values()

dict_values([a    1
b    2
c    3
dtype: int64, a    1
b    2
z    3
d    4
dtype: int64, a    10
b    11
c    12
d    13
z    14
dtype: int64])

In [69]:
df['four']=df['two']+df['three']

In [70]:
df

one  two  three  four
a  1.0  1.0     10  11.0
b  2.0  2.0     11  13.0
c  3.0  NaN     12   NaN
d  NaN  4.0     13  17.0
z  NaN  3.0     14  17.0