In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import pickle

In [2]:
data = pd.read_csv('hiring.csv')
data

experience  test_score  interview_score  salary
0        NaN         8.0                9   50000
1        NaN         8.0                6   45000
2       five         6.0                7   60000
3        two        10.0               10   65000
4      seven         9.0                6   70000
5      three         7.0               10   62000
6        ten         NaN                7   72000
7     eleven         7.0                8   80000

In [18]:
from pandas.api.types import is_numeric_dtype as nd

In [35]:
def convert(w):
    word = {0:0,'zero':0,'one':1, 'two':2, 'three':3, 'four':4, 'five':5, 'six':6, 'seven':7, 'eight':8,
                'nine':9, 'ten':10, 'eleven':11, 'twelve':12}
    return(word[w])

In [5]:
new = data

In [28]:
new['experience'].fillna(0,inplace=True)

In [29]:
new

experience  test_score  interview_score  salary
0          0         8.0                9   50000
1          0         8.0                6   45000
2       five         6.0                7   60000
3        two        10.0               10   65000
4      seven         9.0                6   70000
5      three         7.0               10   62000
6        ten         NaN                7   72000
7     eleven         7.0                8   80000

In [36]:
L=[]
for i in new['experience']:
    L.append(convert(i))
L

[0, 0, 5, 2, 7, 3, 10, 11]

In [37]:
new['experience']=L
new

experience  test_score  interview_score  salary
0           0         8.0                9   50000
1           0         8.0                6   45000
2           5         6.0                7   60000
3           2        10.0               10   65000
4           7         9.0                6   70000
5           3         7.0               10   62000
6          10         NaN                7   72000
7          11         7.0                8   80000

In [40]:
new['test_score'].fillna(new['test_score'].mean(),inplace=True)

In [54]:
nn = new.drop('salary',axis='columns')
nn

experience  test_score  interview_score
0           0    8.000000                9
1           0    8.000000                6
2           5    6.000000                7
3           2   10.000000               10
4           7    9.000000                6
5           3    7.000000               10
6          10    7.857143                7
7          11    7.000000                8

In [43]:
from sklearn.linear_model import LinearRegression
reg = LinearRegression()

In [50]:
reg.fit(nn,data.salary)

LinearRegression()

In [51]:
reg.coef_

array([2827.63404314, 1912.93803053, 2196.9753141 ])

In [52]:
reg.predict([[2,9,6]])

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([53290.89255945])

In [53]:
reg.predict([[12,10,10]])

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([92268.07227784])

In [55]:
reg.predict([[5,6,7]])

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([58231.95591138])